version: '3.9'

services:
  nginx:
    build:
      context: ./
      dockerfile: ./DockerFiles/NGINX.Dockerfile
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./application:/var/www/app:rw"
  php:
    build:
      context: ./
      dockerfile: ./DockerFiles/PHP.Dockerfile
    container_name: php
    ports:
      - "9000:9000"
    volumes:
      - "./application:/var/www/app:rw"
    working_dir: "/var/www/app"

  mariadb:
    image: mariadb:latest
    volumes:
      - "./db:/var/lib/mysql:rw"
    restart: always
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "s3rv3r"
      MYSQL_DATABASE: "app"
      MYSQL_USER: "appuser"
      MYSQL_PASSWORD: "N40C0nt0"
